# Define here the models for your scraped items
#
# See documentation in:
# https://docs.scrapy.org/en/latest/topics/items.html

import scrapy


class PetrovichparserItem(scrapy.Item):

    Name = scrapy.Field()
    VariantName = scrapy.Field()
    Vendor = scrapy.Field()
    Type = scrapy.Field()
    Article = scrapy.Field()
    Tags = scrapy.Field()
    Description = scrapy.Field()
    Details = scrapy.Field()
    Image = scrapy.Field()
    photo = scrapy.Field()
    Price = scrapy.Field()
    Currency = scrapy.Field()
    Currency_Value = scrapy.Field()
    OldPrice = scrapy.Field()
    CurrencyMinimum = scrapy.Field()
    CurrencyMinimum_Value = scrapy.Field()
    Weight = scrapy.Field()
    PackageSize1 = scrapy.Field()
    PackageSize2 = scrapy.Field()
    PackageSize3 = scrapy.Field()
    Units = scrapy.Field()
    Units_Value = scrapy.Field()
    StockUnits = scrapy.Field()
    TopSellingMultiplier = scrapy.Field()
    TopSellingAddition = scrapy.Field()
    VAT = scrapy.Field()
    SalesNotes = scrapy.Field()
    ItemID = scrapy.Field()
    ImportSourceID = scrapy.Field()
    RateTotal = scrapy.Field()
    RateCount = scrapy.Field()
    Material = scrapy.Field()
    Size = scrapy.Field()
    Variant_Volume = scrapy.Field()
    ForUse = scrapy.Field()
    Indications = scrapy.Field()
    Composition = scrapy.Field()
    Effect = scrapy.Field()
    Specification = scrapy.Field()
    TabsQty = scrapy.Field()
    HasVariants = scrapy.Field()
    NoYandex = scrapy.Field()
    NoGoogle = scrapy.Field()
    NoMail = scrapy.Field()
    TopSales = scrapy.Field()
    ActionText = scrapy.Field()
    Action = scrapy.Field()
    Complect = scrapy.Field()
    MarketDesc = scrapy.Field()
    ExpressDelivery = scrapy.Field()
    Data = scrapy.Field()
    Data2 = scrapy.Field()
    ProdType = scrapy.Field()
    Param = scrapy.Field()
    ParamCompleted = scrapy.Field()
    Strana_proizvoditelya = scrapy.Field()
    Obem = scrapy.Field()
    Ves = scrapy.Field()
    Cena_Optovaya = scrapy.Field()
    Min_partiya = scrapy.Field()
    NDS = scrapy.Field()
    BarCode = scrapy.Field()
    SKU = scrapy.Field()
    VendorCode = scrapy.Field()
    Length = scrapy.Field()
    Width = scrapy.Field()
    Height = scrapy.Field()
    Color = scrapy.Field()
    Belki = scrapy.Field()
    ZHiry = scrapy.Field()
    Uglevody = scrapy.Field()
    Fruktoza = scrapy.Field()
    Saxaroza = scrapy.Field()
    Energeticheskaya_cennost = scrapy.Field()
    Srok_godnosti_dnej = scrapy.Field()
    InnerID = scrapy.Field()
    IdentifierExists = scrapy.Field()
    Pitatelnaya_cennost = scrapy.Field()
    Vitaminy_i_mineraly = scrapy.Field()
    Usloviya_xraneniya = scrapy.Field()
    MinOrderQty = scrapy.Field()
    On_Sklad = scrapy.Field()
    MainGood = scrapy.Field()
    SimilarProductIds = scrapy.Field()
    Keyword = scrapy.Field()
    ncTitle = scrapy.Field()
    ncKeywords = scrapy.Field()
    ncDescription = scrapy.Field()
    ncSMO_Title = scrapy.Field()
    ncSMO_Description = scrapy.Field()
    ncSMO_Image = scrapy.Field()
    category = scrapy.Field()
    elem_id = scrapy.Field()

    link_product = scrapy.Field()
    link_api_product = scrapy.Field()

    _id = scrapy.Field()
